enum SparkZCoreRPCId
{
    SPARKZ_RPC_CORE_HELLO = 780001,
    SPARKZ_RPC_CORE_CONFIG_REQUEST = 780010,
    SPARKZ_RPC_CORE_CONFIG_RESPONSE = 780011,
    SPARKZ_RPC_CORE_EVENT_NOTIFY_SYNC = 780012,

    SPARKZ_RPC_GROUP_RESERVED_START = 781000,
    SPARKZ_RPC_GROUP_HELLO = 781001,

    SPARKZ_RPC_GROUP_MARKER_CREATE_REQUEST = 781100,
    SPARKZ_RPC_GROUP_MARKER_UPDATE_REQUEST = 781101,
    SPARKZ_RPC_GROUP_MARKER_DELETE_REQUEST = 781102,
    SPARKZ_RPC_GROUP_MARKER_SYNC = 781103,
    SPARKZ_RPC_GROUP_MARKER_CLEAR_SYNC = 781104,

    SPARKZ_RPC_GROUP_CREATE_REQUEST = 781300,
    SPARKZ_RPC_GROUP_INVITE_REQUEST = 781301,
    SPARKZ_RPC_GROUP_INVITE_RESPONSE = 781302,
    SPARKZ_RPC_GROUP_LEAVE_REQUEST = 781303,
    SPARKZ_RPC_GROUP_KICK_REQUEST = 781304,
    SPARKZ_RPC_GROUP_PROMOTE_REQUEST = 781305,
    SPARKZ_RPC_GROUP_SYNC = 781306,
    SPARKZ_RPC_GROUP_INVITE_SYNC = 781307,
    SPARKZ_RPC_GROUP_INVITE_RESULT_SYNC = 781308,
    SPARKZ_RPC_GROUP_PERMISSION_REQUEST = 781309,

    SPARKZ_RPC_GROUP_PING_CREATE_REQUEST = 781600,
    SPARKZ_RPC_GROUP_PING_SYNC = 781601,
    SPARKZ_RPC_GROUP_PING_EXPIRE_SYNC = 781602,
    SPARKZ_RPC_GROUP_LAST_DEATH_SYNC = 781603,

    SPARKZ_RPC_GROUP_EVENT_MARKER_SYNC = 781700,
    SPARKZ_RPC_GROUP_EVENT_MARKER_CLEAR_SYNC = 781701,

    SPARKZ_RPC_GROUP_RESERVED_END = 781999,

    SPARKZ_RPC_BASE_STATUS_REQUEST = 782000,
    SPARKZ_RPC_BASE_STATUS_RESPONSE = 782001,
    SPARKZ_RPC_BASE_PAY_REQUEST = 782002,
    SPARKZ_RPC_BASE_GIVEUP_REQUEST = 782003
}

class SparkZCoreRPC
{
    static bool IsCoreRPC(int rpcId)
    {
        return rpcId >= SparkZCoreConstants.RPC_RANGE_CORE_MIN && rpcId <= SparkZCoreConstants.RPC_RANGE_CORE_MAX;
    }

    static bool IsGroupRPC(int rpcId)
    {
        return rpcId >= SparkZCoreConstants.RPC_RANGE_GROUP_MIN && rpcId <= SparkZCoreConstants.RPC_RANGE_GROUP_MAX;
    }

    static bool IsBaseRPC(int rpcId)
    {
        return rpcId >= SparkZCoreConstants.RPC_RANGE_BASE_MIN && rpcId <= SparkZCoreConstants.RPC_RANGE_BASE_MAX;
    }

    static bool IsSparkZRPC(int rpcId)
    {
        return IsCoreRPC(rpcId) || IsGroupRPC(rpcId) || IsBaseRPC(rpcId);
    }
}
